### ISSUE TITLE
Hardware/Schematics?

### ISSUE THREAD

**Issue by EvergreenCartoons** [jarpoole/ethernet-mitm#51]
Got to here from your awesome demo video, was wondering if you intended on open sourcing the hardware schematic as well as the software side? 

I'd love to do some experimenting with this myself at some point, its an awesome demonstration of what an attacker can do with "access to an exposed ethernet cable", and I suspect the hardware side will be *very* enlightening.

**Comment by jarpoole** [comment]
Yep! Exams and holidays had me a little busy and I still haven't uploaded all the mechanical files but see the electrical folder for schematics, layout and BOM!
